### ISSUE TITLE
private method `warn' called for nil:NilClass

### ISSUE THREAD

**Issue by zhangtenghai** [beansmile/tingyun_rpm#3]
NoMethodError - private method `warn' called for nil:NilClass:
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:75:in `rescue in call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:78:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  rack (1.6.8) lib/rack/etag.rb:24:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  rack (1.6.8) lib/rack/conditionalget.rb:25:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  rack (1.6.8) lib/rack/head.rb:13:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  remotipart (1.3.1) lib/remotipart/middleware.rb:32:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  rack (1.6.8) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.8) lib/rack/session/abstract/id.rb:220:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  activerecord (4.2.6) lib/active_record/query_cache.rb:36:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  activerecord (4.2.6) lib/active_record/migration.rb:377:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  web-console (3.3.0) lib/web_console/middleware.rb:131:in `call_app'
  web-console (3.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (3.3.0) lib/web_console/middleware.rb:18:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/headers.rb:16:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  rack (1.6.8) lib/rack/runtime.rb:18:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  rack (1.6.8) lib/rack/lock.rb:17:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  rack (1.6.8) lib/rack/sendfile.rb:113:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  tingyun_rpm (1.4.1) lib/ting_yun/instrumentation/middleware_tracing.rb:64:in `call'
  rack (1.6.8) lib/rack/content_length.rb:15:in `call'
  thin (1.7.0) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.7.0) lib/thin/connection.rb:84:in `pre_process'
  thin (1.7.0) lib/thin/connection.rb:53:in `process'
  thin (1.7.0) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run'
  thin (1.7.0) lib/thin/backends/base.rb:73:in `start'
  thin (1.7.0) lib/thin/server.rb:162:in `start'
  rack (1.6.8) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.8) lib/rack/server.rb:287:in `start'
  railties (4.2.6) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.6) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `<main>'

**Comment by rainchen** [comment]
tingyun_rpm released v1.4.2 @ September 27, 2017
